#!/bin/bash

set -ex

zabbix_cfg="/etc/zabbix/zabbix_server.conf"

set -i "s/^DBHost=.*/DBHost=/" $zabbix_cfg
set -i "s/^DBName=.*/DBName=/" $zabbix_cfg
set -i "s/^DBUser=.*/DBUser=/" $zabbix_cfg
set -i "s/^DBPassword=.*/DBPassword=/" $zabbix_cfg
set -i "s/^DBName=.*/DBName=/" $zabbix_cfg

rm -f /etc/zabbix/dbconfig.php

