#!/bin/bash

set -ex

cat contrib/debconf-selections | debconf-set-selections

apt-get install -y zabbix-server-mysql zabbix-frontend-php php5-mysql

#Configure alias at Apache2
a2enmod alias
cp /usr/share/doc/zabbix-frontend-php/examples/apache.conf /etc/apache2/conf-available/zabbix.conf
a2enconf zabbix.conf

#Change php.ini to best zabbix-frontend-php usage
php_ini="/etc/php5/apache2/php.ini"
sed -i "/^post_max_size =.*/c\post_max_size = 16M" $php_ini
sed -i "/^max_execution_time =.*/c\max_execution_time = 300" $php_ini
sed -i "/^max_input_time =.*/c\max_input_time = 300" $php_ini
sed -i "/^;date.timezone =.*/c\date.timezone = UTC" $php_ini

#Enable Zabbix Server as a daemon
zabbix_default_cfg="/etc/default/zabbix-server"
sed -i "s/^START=no/START=yes/" $zabbix_default_cfg
